import { and, eq, exists, inArray, isNull, or, sql } from "drizzle-orm";
import type { Db } from "../../../shared/db/client";
import { expenseGroupMember, splitExpense, splitShare } from "../../../shared/db/schema";
import type { CreateSplitExpenseInput, SplitExpense, SplitMode, SplitShare, UpdateSplitExpenseFields } from "../domain/split-expense";
import type { ListExpensesFilter, SplitExpenseRepository } from "../domain/split-expense-repository";

type SplitExpenseRow = typeof splitExpense.$inferSelect;
type SplitShareRow = typeof splitShare.$inferSelect;

function toShare(row: SplitShareRow): SplitShare {
  return { userId: row.userId, amount: row.amount };
}

function toExpense(row: SplitExpenseRow, shareRows: SplitShareRow[]): SplitExpense {
  return {
    id: row.id,
    groupId: row.groupId,
    payerUserId: row.payerUserId,
    createdByUserId: row.createdByUserId,
    amount: row.amount,
    currency: row.currency,
    description: row.description,
    day: row.day,
    splitMode: row.splitMode as SplitMode,
    shares: shareRows.map(toShare),
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

function sharesToRows(expenseId: string, shares: SplitShare[]) {
  return shares.map((share) => ({ expenseId, userId: share.userId, amount: share.amount }));
}

/**
 * `userId` participates in an expense when they are its payer or hold a
 * share — an `EXISTS` against `split_share` rather than a join, so it never
 * duplicates the expense row per share. Shared by every branch of
 * `listForUser`'s filter.
 */
function participatesIn(db: Db, userId: string) {
  return or(
    eq(splitExpense.payerUserId, userId),
    exists(
      db
        .select({ one: sql`1` })
        .from(splitShare)
        .where(and(eq(splitShare.expenseId, splitExpense.id), eq(splitShare.userId, userId))),
    ),
  );
}

/**
 * `userId` can see a *grouped* expense by being a member of its group, with
 * no share of their own — the same definition `isParticipant` uses in the
 * application layer. Without this the unfiltered listing and the
 * `?group_id=` listing disagreed about what the caller can see: a group
 * expense they hold no share in appeared in the second and not the first.
 */
function memberOfExpenseGroup(db: Db, userId: string) {
  return exists(
    db
      .select({ one: sql`1` })
      .from(expenseGroupMember)
      .where(and(eq(expenseGroupMember.groupId, splitExpense.groupId), eq(expenseGroupMember.userId, userId))),
  );
}

/** Driven adapter: implements SplitExpenseRepository via Drizzle + Neon. */
export class DrizzleSplitExpenseRepository implements SplitExpenseRepository {
  constructor(private readonly getDb: () => Db) {}

  /**
   * Writes the expense row and its share rows in a single `db.batch` — the
   * only way to keep them atomic on `drizzle-orm/neon-http`, which has no
   * `transaction()` support. `input.id` is generated by the caller
   * (`crypto.randomUUID()`) precisely so the share rows' `expense_id` is
   * known before either statement is sent (design.md).
   */
  async create(input: CreateSplitExpenseInput): Promise<SplitExpense> {
    const db = this.getDb();
    const now = new Date();
    const expenseInsert = db.insert(splitExpense).values({
      id: input.id,
      groupId: input.groupId,
      payerUserId: input.payerUserId,
      createdByUserId: input.createdByUserId,
      amount: input.amount,
      currency: input.currency,
      description: input.description,
      day: input.day,
      splitMode: input.splitMode,
      createdAt: now,
      updatedAt: now,
    });
    const shareInsert = db.insert(splitShare).values(sharesToRows(input.id, input.shares));
    await db.batch([expenseInsert, shareInsert]);

    return {
      id: input.id,
      groupId: input.groupId,
      payerUserId: input.payerUserId,
      createdByUserId: input.createdByUserId,
      amount: input.amount,
      currency: input.currency,
      description: input.description,
      day: input.day,
      splitMode: input.splitMode,
      shares: input.shares,
      createdAt: now,
      updatedAt: now,
    };
  }

  async findById(id: string): Promise<SplitExpense | null> {
    const db = this.getDb();
    const [row] = await db.select().from(splitExpense).where(eq(splitExpense.id, id)).limit(1);
    if (!row) return null;
    const shares = await db.select().from(splitShare).where(eq(splitShare.expenseId, id));
    return toExpense(row, shares);
  }

  /**
   * Replaces the row and atomically swaps its shares: delete every existing
   * share, insert the new set, update the row's fields — all in one batch
   * (design.md: never a two-step insert that can leave shares that don't sum
   * to the amount). The existence check happens before the batch is built —
   * `update`'s own row lock inside a batch is not something we can branch on
   * mid-batch, and the application layer already re-checks existence via
   * `findById` before ever calling this.
   */
  async update(id: string, fields: UpdateSplitExpenseFields, now: Date): Promise<SplitExpense | null> {
    const db = this.getDb();
    const [existing] = await db.select({ id: splitExpense.id }).from(splitExpense).where(eq(splitExpense.id, id)).limit(1);
    if (!existing) return null;

    const deleteShares = db.delete(splitShare).where(eq(splitShare.expenseId, id));
    const insertShares = db.insert(splitShare).values(sharesToRows(id, fields.shares));
    const updateExpense = db
      .update(splitExpense)
      .set({
        payerUserId: fields.payerUserId,
        amount: fields.amount,
        currency: fields.currency,
        description: fields.description,
        day: fields.day,
        splitMode: fields.splitMode,
        updatedAt: now,
      })
      .where(eq(splitExpense.id, id));
    await db.batch([deleteShares, insertShares, updateExpense]);

    return this.findById(id);
  }

  /** `on delete cascade` on `split_share.expense_id` takes the shares with it — a single statement is enough. */
  async delete(id: string): Promise<boolean> {
    const deleted = await this.getDb().delete(splitExpense).where(eq(splitExpense.id, id)).returning({ id: splitExpense.id });
    return deleted.length > 0;
  }

  /**
   * `userId`'s expenses matching `filter`, scoped in SQL (design.md: never a
   * post-filter). `group_id=<id>` returns every expense in that group — the
   * use case has already verified the caller is a member before calling this,
   * and group membership counts as participation independent of shares.
   * `with=<userId>` is groupless expenses where both sides participate.
   * Neither given lists everything the caller participates in — including
   * grouped expenses they can see through membership alone, so the
   * unfiltered listing and the `group_id=` listing agree on what is visible.
   */
  async listForUser(userId: string, filter: ListExpensesFilter): Promise<SplitExpense[]> {
    const db = this.getDb();

    const where =
      filter.groupId !== undefined
        ? eq(splitExpense.groupId, filter.groupId)
        : filter.withUserId !== undefined
          ? and(isNull(splitExpense.groupId), participatesIn(db, userId), participatesIn(db, filter.withUserId))
          : or(participatesIn(db, userId), memberOfExpenseGroup(db, userId));

    const rows = await db.select().from(splitExpense).where(where);
    if (rows.length === 0) return [];

    const shares = await db.select().from(splitShare).where(
      inArray(
        splitShare.expenseId,
        rows.map((row) => row.id),
      ),
    );
    const sharesByExpense = new Map<string, SplitShareRow[]>();
    for (const share of shares) {
      const list = sharesByExpense.get(share.expenseId) ?? [];
      list.push(share);
      sharesByExpense.set(share.expenseId, list);
    }
    return rows.map((row) => toExpense(row, sharesByExpense.get(row.id) ?? []));
  }
}
