import { and, eq, exists, inArray, isNull, or, sql } from "drizzle-orm";
import type { Db } from "../../../shared/db/client";
import { expenseGroupMember, splitExpense, splitShare, users } from "../../../shared/db/schema";
import type { CreateSplitExpenseInput, SplitExpense, SplitMode, SplitShare, SplitShareInput, UpdateSplitExpenseFields } from "../domain/split-expense";
import { splitDisplayName } from "../domain/display-name";
import type { ListExpensesFilter, SplitExpenseRepository } from "../domain/split-expense-repository";
import type { SplitSpendingAmount } from "../domain/split-spending";
import type { SplitSpendingRepository } from "../domain/split-spending-repository";

type SplitExpenseRow = typeof splitExpense.$inferSelect;
type SplitShareRow = typeof splitShare.$inferSelect;

/**
 * Names come from a `users` join, not from the writer's friend list: a share
 * holder can see co-participants who are neither their friend nor in any
 * group they belong to, so nothing else on the client can resolve them.
 */
function toShare(row: SplitShareRow, name: string): SplitShare {
  return { userId: row.userId, amount: row.amount, displayName: name };
}

function toExpense(row: SplitExpenseRow, shareRows: SplitShareRow[], names: Map<string, string>): SplitExpense {
  return {
    id: row.id,
    groupId: row.groupId,
    payerUserId: row.payerUserId,
    payerDisplayName: names.get(row.payerUserId) ?? row.payerUserId,
    createdByUserId: row.createdByUserId,
    amount: row.amount,
    currency: row.currency,
    description: row.description,
    day: row.day,
    splitMode: row.splitMode as SplitMode,
    shares: shareRows.map((share) => toShare(share, names.get(share.userId) ?? share.userId)),
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

function sharesToRows(expenseId: string, shares: SplitShareInput[]) {
  return shares.map((share) => ({ expenseId, userId: share.userId, amount: share.amount }));
}

/**
 * `userId` participates in an expense when they are its payer or hold a
 * share — an `EXISTS` against `split_share` rather than a join, so it never
 * duplicates the expense row per share. Shared by every branch of
 * `listForUser`'s filter.
 */
function participatesIn(db: Db, userId: string) {
  return or(
    eq(splitExpense.payerUserId, userId),
    exists(
      db
        .select({ one: sql`1` })
        .from(splitShare)
        .where(and(eq(splitShare.expenseId, splitExpense.id), eq(splitShare.userId, userId))),
    ),
  );
}

/**
 * `userId` can see a *grouped* expense by being a member of its group, with
 * no share of their own — the same definition `isParticipant` uses in the
 * application layer. Without this the unfiltered listing and the
 * `?group_id=` listing disagreed about what the caller can see: a group
 * expense they hold no share in appeared in the second and not the first.
 */
function memberOfExpenseGroup(db: Db, userId: string) {
  return exists(
    db
      .select({ one: sql`1` })
      .from(expenseGroupMember)
      .where(and(eq(expenseGroupMember.groupId, splitExpense.groupId), eq(expenseGroupMember.userId, userId))),
  );
}

/** Driven adapter: implements SplitExpenseRepository via Drizzle + Neon; also SplitSpendingRepository (see `splitSpendingForUser`) since both read `split_expense`/`split_share`. */
export class DrizzleSplitExpenseRepository implements SplitExpenseRepository, SplitSpendingRepository {
  constructor(private readonly getDb: () => Db) {}

  /**
   * Writes the expense row and its share rows in a single `db.batch` — the
   * only way to keep them atomic on `drizzle-orm/neon-http`, which has no
   * `transaction()` support. `input.id` is generated by the caller
   * (`crypto.randomUUID()`) precisely so the share rows' `expense_id` is
   * known before either statement is sent (design.md).
   */
  async create(input: CreateSplitExpenseInput): Promise<SplitExpense> {
    const db = this.getDb();
    const now = new Date();
    const expenseInsert = db.insert(splitExpense).values({
      id: input.id,
      groupId: input.groupId,
      payerUserId: input.payerUserId,
      createdByUserId: input.createdByUserId,
      amount: input.amount,
      currency: input.currency,
      description: input.description,
      day: input.day,
      splitMode: input.splitMode,
      createdAt: now,
      updatedAt: now,
    });
    const shareInsert = db.insert(splitShare).values(sharesToRows(input.id, input.shares));
    await db.batch([expenseInsert, shareInsert]);

    const names = await this.namesFor([input.payerUserId, ...input.shares.map((share) => share.userId)]);
    return {
      id: input.id,
      groupId: input.groupId,
      payerUserId: input.payerUserId,
      payerDisplayName: names.get(input.payerUserId) ?? input.payerUserId,
      createdByUserId: input.createdByUserId,
      amount: input.amount,
      currency: input.currency,
      description: input.description,
      day: input.day,
      splitMode: input.splitMode,
      shares: input.shares.map((share) => ({ ...share, displayName: names.get(share.userId) ?? share.userId })),
      createdAt: now,
      updatedAt: now,
    };
  }



  async findById(id: string): Promise<SplitExpense | null> {
    const db = this.getDb();
    const [row] = await db.select().from(splitExpense).where(eq(splitExpense.id, id)).limit(1);
    if (!row) return null;
    const shares = await db.select().from(splitShare).where(eq(splitShare.expenseId, id));
    // The payer is included deliberately: they need not hold a share.
    return toExpense(row, shares, await this.namesFor([row.payerUserId, ...shares.map((share) => share.userId)]));
  }

  /**
   * Replaces the row and atomically swaps its shares: delete every existing
   * share, insert the new set, update the row's fields — all in one batch
   * (design.md: never a two-step insert that can leave shares that don't sum
   * to the amount). The existence check happens before the batch is built —
   * `update`'s own row lock inside a batch is not something we can branch on
   * mid-batch, and the application layer already re-checks existence via
   * `findById` before ever calling this.
   */
  async update(id: string, fields: UpdateSplitExpenseFields, now: Date): Promise<SplitExpense | null> {
    const db = this.getDb();
    const [existing] = await db.select({ id: splitExpense.id }).from(splitExpense).where(eq(splitExpense.id, id)).limit(1);
    if (!existing) return null;

    const deleteShares = db.delete(splitShare).where(eq(splitShare.expenseId, id));
    const insertShares = db.insert(splitShare).values(sharesToRows(id, fields.shares));
    const updateExpense = db
      .update(splitExpense)
      .set({
        payerUserId: fields.payerUserId,
        amount: fields.amount,
        currency: fields.currency,
        description: fields.description,
        day: fields.day,
        splitMode: fields.splitMode,
        updatedAt: now,
      })
      .where(eq(splitExpense.id, id));
    await db.batch([deleteShares, insertShares, updateExpense]);

    return this.findById(id);
  }

  /** `on delete cascade` on `split_share.expense_id` takes the shares with it — a single statement is enough. */
  async delete(id: string): Promise<boolean> {
    const deleted = await this.getDb().delete(splitExpense).where(eq(splitExpense.id, id)).returning({ id: splitExpense.id });
    return deleted.length > 0;
  }

  /**
   * `userId`'s expenses matching `filter`, scoped in SQL (design.md: never a
   * post-filter). `group_id=<id>` returns every expense in that group — the
   * use case has already verified the caller is a member before calling this,
   * and group membership counts as participation independent of shares.
   * `with=<userId>` is groupless expenses where both sides participate.
   * Neither given lists everything the caller participates in — including
   * grouped expenses they can see through membership alone, so the
   * unfiltered listing and the `group_id=` listing agree on what is visible.
   */
  async listForUser(userId: string, filter: ListExpensesFilter): Promise<SplitExpense[]> {
    const db = this.getDb();

    const where =
      filter.groupId !== undefined
        ? eq(splitExpense.groupId, filter.groupId)
        : filter.withUserId !== undefined
          ? and(isNull(splitExpense.groupId), participatesIn(db, userId), participatesIn(db, filter.withUserId))
          : or(participatesIn(db, userId), memberOfExpenseGroup(db, userId));

    const rows = await db.select().from(splitExpense).where(where);
    if (rows.length === 0) return [];

    const shares = await db.select().from(splitShare).where(
      inArray(
        splitShare.expenseId,
        rows.map((row) => row.id),
      ),
    );
    const sharesByExpense = new Map<string, SplitShareRow[]>();
    for (const share of shares) {
      const list = sharesByExpense.get(share.expenseId) ?? [];
      list.push(share);
      sharesByExpense.set(share.expenseId, list);
    }
    const names = await this.namesFor([...rows.map((row) => row.payerUserId), ...shares.map((share) => share.userId)]);
    return rows.map((row) => toExpense(row, sharesByExpense.get(row.id) ?? [], names));
  }

  /**
   * `userId`'s own `split_share.amount` total per currency for expenses whose
   * `day` falls in `month`, aggregated in SQL (`GROUP BY` currency) — never
   * by loading shares into memory (design.md). Currency lives on
   * `split_expense`, not `split_share`, hence the join. Deliberately counts
   * the payer's own share (they really spent it) and never a settlement
   * (settlements live in `split_settlement`, a separate table there is
   * nothing to filter out of) — the opposite of `DrizzleBalanceRepository`,
   * which excludes the payer's own share because it answers "who owes whom",
   * not "what did I spend" (see `SplitSpendingRepository`).
   */
  async splitSpendingForUser(userId: string, month: string): Promise<SplitSpendingAmount[]> {
    const db = this.getDb();
    const rows = await db
      .select({ currency: splitExpense.currency, amount: sql<string>`SUM(${splitShare.amount})` })
      .from(splitShare)
      .innerJoin(splitExpense, eq(splitExpense.id, splitShare.expenseId))
      .where(and(eq(splitShare.userId, userId), sql`to_char(${splitExpense.day}, 'YYYY-MM') = ${month}`))
      .groupBy(splitExpense.currency);
    return rows.map((row) => ({ currency: row.currency, amount: Number(row.amount) }));
  }

  /**
   * One lookup for every distinct participant across the whole result, rather
   * than a join that would duplicate the expense row per share.
   */
  private async namesFor(userIds: string[]): Promise<Map<string, string>> {
    const distinct = [...new Set(userIds)];
    if (distinct.length === 0) return new Map();
    const rows = await this.getDb()
      .select({ id: users.id, displayName: users.displayName, email: users.email })
      .from(users)
      .where(inArray(users.id, distinct));
    return new Map(rows.map((row) => [row.id, splitDisplayName(row.displayName, row.email)]));
  }
}
