import { and, eq, exists, inArray, isNull, or, sql } from "drizzle-orm";
import type { Db } from "../../../shared/db/client";
import { expenseGroupMember, splitActivity, splitExpense, splitShare, users } from "../../../shared/db/schema";
import { grouplessAudience } from "./split-activity-audience";
import type { CreateSplitExpenseInput, SplitExpense, SplitMode, SplitShare, SplitShareInput, UpdateSplitExpenseFields } from "../domain/split-expense";
import { splitDisplayName } from "../domain/display-name";
import type { ListExpensesFilter, SplitExpenseRepository } from "../domain/split-expense-repository";
import type { SplitSpendingAmount } from "../domain/split-spending";
import type { SplitSpendingRepository } from "../domain/split-spending-repository";

type SplitExpenseRow = typeof splitExpense.$inferSelect;
type SplitShareRow = typeof splitShare.$inferSelect;

/**
 * Names come from a `users` join, not from the writer's friend list: a share
 * holder can see co-participants who are neither their friend nor in any
 * group they belong to, so nothing else on the client can resolve them.
 */
function toShare(row: SplitShareRow, name: string): SplitShare {
  return { userId: row.userId, amount: row.amount, displayName: name };
}

function toExpense(row: SplitExpenseRow, shareRows: SplitShareRow[], names: Map<string, string>): SplitExpense {
  return {
    id: row.id,
    groupId: row.groupId,
    payerUserId: row.payerUserId,
    payerDisplayName: names.get(row.payerUserId) ?? row.payerUserId,
    createdByUserId: row.createdByUserId,
    amount: row.amount,
    currency: row.currency,
    description: row.description,
    day: row.day,
    splitMode: row.splitMode as SplitMode,
    shares: shareRows.map((share) => toShare(share, names.get(share.userId) ?? share.userId)),
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

function sharesToRows(expenseId: string, shares: SplitShareInput[]) {
  return shares.map((share) => ({ expenseId, userId: share.userId, amount: share.amount }));
}

/**
 * `userId` participates in an expense when they are its payer or hold a
 * share — an `EXISTS` against `split_share` rather than a join, so it never
 * duplicates the expense row per share. Shared by every branch of
 * `listForUser`'s filter.
 */
function participatesIn(db: Db, userId: string) {
  return or(
    eq(splitExpense.payerUserId, userId),
    exists(
      db
        .select({ one: sql`1` })
        .from(splitShare)
        .where(and(eq(splitShare.expenseId, splitExpense.id), eq(splitShare.userId, userId))),
    ),
  );
}

/**
 * `userId` can see a *grouped* expense by being a member of its group, with
 * no share of their own — the same definition `isParticipant` uses in the
 * application layer. Without this the unfiltered listing and the
 * `?group_id=` listing disagreed about what the caller can see: a group
 * expense they hold no share in appeared in the second and not the first.
 */
function memberOfExpenseGroup(db: Db, userId: string) {
  return exists(
    db
      .select({ one: sql`1` })
      .from(expenseGroupMember)
      .where(and(eq(expenseGroupMember.groupId, splitExpense.groupId), eq(expenseGroupMember.userId, userId))),
  );
}

/** Driven adapter: implements SplitExpenseRepository via Drizzle + Neon; also SplitSpendingRepository (see `splitSpendingForUser`) since both read `split_expense`/`split_share`. */
export class DrizzleSplitExpenseRepository implements SplitExpenseRepository, SplitSpendingRepository {
  constructor(private readonly getDb: () => Db) {}

  /**
   * Writes the expense row, its share rows and its activity entry in a single
   * `db.batch` — the only way to keep them atomic on `drizzle-orm/neon-http`,
   * which has no `transaction()` support. `input.id` is generated by the caller
   * (`crypto.randomUUID()`) precisely so the share rows' `expense_id` is
   * known before either statement is sent (design.md).
   *
   * The actor is `createdByUserId`: whoever recorded the expense, which need
   * not be the payer. No extra parameter is needed here, unlike `update` and
   * `delete`, where the caller's identity is not part of the input.
   */
  async create(input: CreateSplitExpenseInput): Promise<SplitExpense> {
    const db = this.getDb();
    const now = new Date();
    const expenseInsert = db.insert(splitExpense).values({
      id: input.id,
      groupId: input.groupId,
      payerUserId: input.payerUserId,
      createdByUserId: input.createdByUserId,
      amount: input.amount,
      currency: input.currency,
      description: input.description,
      day: input.day,
      splitMode: input.splitMode,
      createdAt: now,
      updatedAt: now,
    });
    const shareInsert = db.insert(splitShare).values(sharesToRows(input.id, input.shares));
    const activityInsert = db.insert(splitActivity).values({
      type: "expense_created",
      actorUserId: input.createdByUserId,
      groupId: input.groupId,
      subjectId: input.id,
      amount: input.amount,
      currency: input.currency,
      description: input.description,
      audienceUserIds:
        input.groupId === null
          ? grouplessAudience([input.createdByUserId, input.payerUserId, ...input.shares.map((share) => share.userId)])
          : null,
      createdAt: now,
    });
    await db.batch([expenseInsert, shareInsert, activityInsert]);

    const names = await this.namesFor([input.payerUserId, ...input.shares.map((share) => share.userId)]);
    return {
      id: input.id,
      groupId: input.groupId,
      payerUserId: input.payerUserId,
      payerDisplayName: names.get(input.payerUserId) ?? input.payerUserId,
      createdByUserId: input.createdByUserId,
      amount: input.amount,
      currency: input.currency,
      description: input.description,
      day: input.day,
      splitMode: input.splitMode,
      shares: input.shares.map((share) => ({ ...share, displayName: names.get(share.userId) ?? share.userId })),
      createdAt: now,
      updatedAt: now,
    };
  }



  async findById(id: string): Promise<SplitExpense | null> {
    const db = this.getDb();
    const [row] = await db.select().from(splitExpense).where(eq(splitExpense.id, id)).limit(1);
    if (!row) return null;
    const shares = await db.select().from(splitShare).where(eq(splitShare.expenseId, id));
    // The payer is included deliberately: they need not hold a share.
    return toExpense(row, shares, await this.namesFor([row.payerUserId, ...shares.map((share) => share.userId)]));
  }

  /**
   * Replaces the row and atomically swaps its shares: delete every existing
   * share, insert the new set, update the row's fields — all in one batch
   * (design.md: never a two-step insert that can leave shares that don't sum
   * to the amount). The existence check happens before the batch is built —
   * `update`'s own row lock inside a batch is not something we can branch on
   * mid-batch, and the application layer already re-checks existence via
   * `findById` before ever calling this.
   *
   * The activity entry joins that batch, and its audience is the union of the
   * participants **before and after** the edit (tasks 1b.5). Taking only the
   * new set would mean the one person an edit can hurt most — someone whose
   * share was removed, and whose balance therefore just changed — is the one
   * person never told about it.
   */
  async update(id: string, fields: UpdateSplitExpenseFields, now: Date, actorUserId: string): Promise<SplitExpense | null> {
    const db = this.getDb();
    const [existing] = await db
      .select({ id: splitExpense.id, groupId: splitExpense.groupId, payerUserId: splitExpense.payerUserId, amount: splitExpense.amount })
      .from(splitExpense)
      .where(eq(splitExpense.id, id))
      .limit(1);
    if (!existing) return null;

    // Read before the batch replaces them. Only a groupless entry freezes an
    // audience, so a grouped expense never pays for this query.
    const previousShareUserIds =
      existing.groupId === null ? (await db.select({ userId: splitShare.userId }).from(splitShare).where(eq(splitShare.expenseId, id))).map((row) => row.userId) : [];

    const deleteShares = db.delete(splitShare).where(eq(splitShare.expenseId, id));
    const insertShares = db.insert(splitShare).values(sharesToRows(id, fields.shares));
    const updateExpense = db
      .update(splitExpense)
      .set({
        payerUserId: fields.payerUserId,
        amount: fields.amount,
        currency: fields.currency,
        description: fields.description,
        day: fields.day,
        splitMode: fields.splitMode,
        updatedAt: now,
      })
      .where(eq(splitExpense.id, id));
    const activityInsert = db.insert(splitActivity).values({
      type: "expense_updated",
      actorUserId,
      groupId: existing.groupId,
      subjectId: id,
      amount: fields.amount,
      // Always recorded, even when the edit left the amount alone: "someone
      // modified this" with no numbers is the entry that says nothing
      // (design.md D6). A reader compares the two.
      previousAmount: existing.amount,
      currency: fields.currency,
      description: fields.description,
      audienceUserIds:
        existing.groupId === null
          ? grouplessAudience([
              actorUserId,
              existing.payerUserId,
              ...previousShareUserIds,
              fields.payerUserId,
              ...fields.shares.map((share) => share.userId),
            ])
          : null,
      createdAt: now,
    });
    await db.batch([deleteShares, insertShares, updateExpense, activityInsert]);

    return this.findById(id);
  }

  /**
   * `on delete cascade` on `split_share.expense_id` takes the shares with it,
   * so one statement deletes the expense — but the activity entry must be
   * written in the same transaction, and it is the one entry that cannot be
   * assembled in JavaScript: after the delete the amount, the description and
   * (for a groupless expense) the entire list of participants are gone, and
   * they are exactly what makes "A deleted the $2000 dinner" readable.
   *
   * So the entry is an `INSERT ... SELECT ... FROM split_expense WHERE id = ?
   * FOR UPDATE`: it takes its snapshot from the row it is about, and it writes
   * **only if that row is there**. A separate existence check before the batch
   * would not do — two concurrent deletes would both pass it, one would match
   * no row and report 404 to its caller, and the timeline would still claim the
   * deletion happened twice.
   *
   * **LOCK: `FOR UPDATE` is what actually closes that race; the condition alone
   * only narrows it.** neon-http's `db.batch` is one **READ COMMITTED**
   * transaction, and in READ COMMITTED *each statement takes its own snapshot*.
   * Without the lock, this INSERT's snapshot can still see the row while the
   * DELETE below — re-evaluated after a concurrent deleter commits — matches
   * nothing: the entry is committed, `false` comes back, the caller gets a 404,
   * and the timeline claims a deletion this request never performed. That is
   * exactly the failure design.md D3 exists to rule out. With `FOR UPDATE` the
   * INSERT takes the row lock, so the two transactions are serialised on it:
   * the loser either blocks until the winner commits and then re-checks against
   * a row that is gone (selecting nothing, and its DELETE matches nothing), or
   * it holds the lock and the other one waits. Exactly one of them writes an
   * entry, and it is the one whose DELETE matched.
   *
   * The `array_agg` in the audience expression does not conflict with it:
   * Postgres rejects `FOR UPDATE` only at a query level that aggregates, and
   * that aggregate lives in a scalar sub-select, a level of its own. `OF e`
   * names the one relation that must be locked; `split_share` need not be, it
   * cascades from the row that is.
   *
   * **UNPROVEN BY THIS SUITE.** PGlite is a single connection with no second
   * session, so no test here can make two of these transactions overlap — the
   * race cannot be reproduced, only argued from Postgres' documented READ
   * COMMITTED behaviour. What the suite does assert is that the emitted SQL
   * carries the lock ("the emitted SQL takes a row lock" in
   * split-activity-write.test.ts). Deleting the `for update` line reddens that
   * case and nothing else.
   *
   * **ORDER: the insert must come BEFORE the delete, and this is not a style
   * choice.** Placed after it, the SELECT runs inside the same transaction
   * where the expense and its cascaded shares are already gone, matches
   * nothing, and silently writes no activity — forever, for every deletion.
   * Nothing would go red: "a delete matching no row records nothing" passes
   * even better when *nothing* is ever recorded. Only a test that deletes a row
   * that really exists and then looks for the entry catches it.
   *
   * **CLOCK: `created_at` comes from the caller's `now` — the Worker's clock —
   * never from the database's `now()`, and this is not interchangeable.** Every
   * other write path passes a JS `Date`, which has millisecond resolution;
   * Postgres' `now()` has microsecond resolution. The keyset cursor for the
   * timeline round-trips the timestamp through a JS `Date` (`toISOString()`),
   * which truncates those microseconds — so a cursor built from a
   * microsecond-precision row lands *above* the rows just below it and they
   * become unreachable by any page, permanently.
   *
   * Resolution is only half of it: the two clocks are also *different clocks*.
   * The Worker's and Neon's can disagree by whatever their skew is, so mixing
   * them puts entries in an order neither machine ever saw — an entry written
   * after another can sort before it, and the cursor then pages straight past
   * whatever fell between. **The Worker's clock is the authoritative one for
   * `created_at`**, because it is the one every other write path already uses
   * and the only one the application can hand to a batch as a value; the
   * database's is used nowhere in this timeline. One clock, one resolution, for
   * all eight write paths. Do not "simplify" this back to `now()` or to
   * the column's `defaultNow()`; PGlite's `now()` is millisecond-resolution, so
   * the test suite cannot see the difference (harness.ts boundary 2) — only
   * Neon can.
   */
  async delete(id: string, actorUserId: string, now: Date): Promise<boolean> {
    const db = this.getDb();
    const activityInsert = db.execute(sql`
      insert into ${splitActivity}
        (type, actor_user_id, group_id, subject_id, amount, currency, description, audience_user_ids, created_at)
      select
        'expense_deleted',
        ${actorUserId}::uuid,
        e.group_id,
        e.id,
        e.amount,
        e.currency,
        e.description,
        case when e.group_id is null then (
          select array_agg(distinct participant)
          from unnest(
            array[${actorUserId}::uuid, e.payer_user_id]
              || coalesce(array(select s.user_id from ${splitShare} s where s.expense_id = e.id), '{}'::uuid[])
          ) as participant
        ) end,
        ${now.toISOString()}::timestamptz
      from ${splitExpense} e
      where e.id = ${id}::uuid
      for update of e
    `);
    const expenseDelete = db.delete(splitExpense).where(eq(splitExpense.id, id)).returning({ id: splitExpense.id });
    const [, deleted] = await db.batch([activityInsert, expenseDelete]);
    return deleted.length > 0;
  }

  /**
   * `userId`'s expenses matching `filter`, scoped in SQL (design.md: never a
   * post-filter). `group_id=<id>` returns every expense in that group — the
   * use case has already verified the caller is a member before calling this,
   * and group membership counts as participation independent of shares.
   * `with=<userId>` is groupless expenses where both sides participate.
   * Neither given lists everything the caller participates in — including
   * grouped expenses they can see through membership alone, so the
   * unfiltered listing and the `group_id=` listing agree on what is visible.
   */
  async listForUser(userId: string, filter: ListExpensesFilter): Promise<SplitExpense[]> {
    const db = this.getDb();

    const where =
      filter.groupId !== undefined
        ? eq(splitExpense.groupId, filter.groupId)
        : filter.withUserId !== undefined
          ? and(isNull(splitExpense.groupId), participatesIn(db, userId), participatesIn(db, filter.withUserId))
          : or(participatesIn(db, userId), memberOfExpenseGroup(db, userId));

    const rows = await db.select().from(splitExpense).where(where);
    if (rows.length === 0) return [];

    const shares = await db.select().from(splitShare).where(
      inArray(
        splitShare.expenseId,
        rows.map((row) => row.id),
      ),
    );
    const sharesByExpense = new Map<string, SplitShareRow[]>();
    for (const share of shares) {
      const list = sharesByExpense.get(share.expenseId) ?? [];
      list.push(share);
      sharesByExpense.set(share.expenseId, list);
    }
    const names = await this.namesFor([...rows.map((row) => row.payerUserId), ...shares.map((share) => share.userId)]);
    return rows.map((row) => toExpense(row, sharesByExpense.get(row.id) ?? [], names));
  }

  /**
   * `userId`'s own `split_share.amount` total per currency for expenses whose
   * `day` falls in `month`, aggregated in SQL (`GROUP BY` currency) — never
   * by loading shares into memory (design.md). Currency lives on
   * `split_expense`, not `split_share`, hence the join. Deliberately counts
   * the payer's own share (they really spent it) and never a settlement
   * (settlements live in `split_settlement`, a separate table there is
   * nothing to filter out of) — the opposite of `DrizzleBalanceRepository`,
   * which excludes the payer's own share because it answers "who owes whom",
   * not "what did I spend" (see `SplitSpendingRepository`).
   */
  async splitSpendingForUser(userId: string, month: string): Promise<SplitSpendingAmount[]> {
    const db = this.getDb();
    const rows = await db
      .select({ currency: splitExpense.currency, amount: sql<string>`SUM(${splitShare.amount})` })
      .from(splitShare)
      .innerJoin(splitExpense, eq(splitExpense.id, splitShare.expenseId))
      .where(and(eq(splitShare.userId, userId), sql`to_char(${splitExpense.day}, 'YYYY-MM') = ${month}`))
      .groupBy(splitExpense.currency);
    return rows.map((row) => ({ currency: row.currency, amount: Number(row.amount) }));
  }

  /**
   * One lookup for every distinct participant across the whole result, rather
   * than a join that would duplicate the expense row per share.
   */
  private async namesFor(userIds: string[]): Promise<Map<string, string>> {
    const distinct = [...new Set(userIds)];
    if (distinct.length === 0) return new Map();
    const rows = await this.getDb()
      .select({ id: users.id, displayName: users.displayName, email: users.email })
      .from(users)
      .where(inArray(users.id, distinct));
    return new Map(rows.map((row) => [row.id, splitDisplayName(row.displayName, row.email)]));
  }
}
