export interface Settlement {
  id: string;
  /** `null` = a groupless/one-off repayment, symmetric with `SplitExpense.groupId`. */
  groupId: string | null;
  /** Who paid — the direction the debt was cleared in. */
  fromUserId: string;
  /** Resolved from `users`, for the same reason `SplitExpense.payerDisplayName` is: the counterpart may be neither a friend of the reader nor a member of a group they belong to. */
  fromDisplayName: string;
  toUserId: string;
  toDisplayName: string;
  /** The repayment, in the currency's minor units. */
  amount: number;
  currency: string;
  /** `YYYY-MM-DD`. */
  day: string;
  note: string | null;
  createdByUserId: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateSettlementInput {
  /** Generated by the application (`crypto.randomUUID()`) before the write. */
  id: string;
  groupId: string | null;
  fromUserId: string;
  toUserId: string;
  amount: number;
  currency: string;
  day: string;
  note: string | null;
  createdByUserId: string;
}
