/** A share as written: identity plus what is owed. Names are a read concern. */
export interface SplitShareInput {
  userId: string;
  /** What this participant owes, in the currency's minor units. Non-negative. */
  amount: number;
  /**
   * Optional repayment schedule (split-installments proposal.md): this
   * holder repays the payer in `periods` monthly instalments of
   * `perPeriodAmount` each, instead of all at once. `amount` above stays the
   * whole share regardless — a schedule says when the money moves, not
   * whether the debt exists.
   */
  schedule?: { periods: number; perPeriodAmount: number };
}

/**
 * A share as read. Carries the participant's name because nothing else can
 * supply it: a share holder can see the whole expense, including
 * co-participants who are neither their friend nor a member of any group they
 * belong to — the friendship rule is checked against the *writer* only
 * (`validate-expense-fields.ts`), while `participation.ts` makes every share
 * holder a viewer. Without this a real person renders as a placeholder in the
 * commonest case there is: a three-way one-off split.
 */
export interface SplitShare extends SplitShareInput {
  displayName: string;
}

export type SplitMode = "equal" | "exact";

export interface SplitExpense {
  id: string;
  /** `null` = a groupless/one-off split between the people named in `shares`. */
  groupId: string | null;
  payerUserId: string;
  /**
   * The payer's name, for the same reason the shares carry theirs — and it
   * cannot be derived from them: a payer who merely fronted the money holds
   * no share at all, so a co-participant reading the expense would have
   * nothing to resolve them with.
   */
  payerDisplayName: string;
  createdByUserId: string;
  /** The total, in the currency's minor units. Always equals the sum of `shares[].amount`. */
  amount: number;
  currency: string;
  description: string;
  /** `YYYY-MM-DD`. */
  day: string;
  /** How the caller originally entered the split — kept only so an edit can default back to the same input mode; the amounts owed are always `shares`, never recomputed from this. */
  splitMode: SplitMode;
  /**
   * The finance category every participant's mirror should land on, as a
   * *name* rather than an id: categories are per-user, so the payer's id
   * means nothing to the people who have to read this (design.md D1). `null`
   * = the payer picked none, and each mirror falls back to its holder's own
   * 其他.
   */
  categoryName: string | null;
  shares: SplitShare[];
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateSplitExpenseInput {
  /** Generated by the application (`crypto.randomUUID()`) before the write, so the shares' `expense_id` is known up front for a single batch (design.md). */
  id: string;
  groupId: string | null;
  payerUserId: string;
  createdByUserId: string;
  amount: number;
  currency: string;
  description: string;
  day: string;
  splitMode: SplitMode;
  categoryName: string | null;
  shares: SplitShareInput[];
}

/** Every mutable field of an expense, replaced atomically. `group_id` and `created_by_user_id` are not here — they are immutable (design.md). */
export interface UpdateSplitExpenseFields {
  payerUserId: string;
  amount: number;
  currency: string;
  description: string;
  day: string;
  splitMode: SplitMode;
  categoryName: string | null;
  shares: SplitShareInput[];
}
