export interface SplitShare {
  userId: string;
  /** What this participant owes, in the currency's minor units. Non-negative. */
  amount: number;
}

export type SplitMode = "equal" | "exact";

export interface SplitExpense {
  id: string;
  /** `null` = a groupless/one-off split between the people named in `shares`. */
  groupId: string | null;
  payerUserId: string;
  createdByUserId: string;
  /** The total, in the currency's minor units. Always equals the sum of `shares[].amount`. */
  amount: number;
  currency: string;
  description: string;
  /** `YYYY-MM-DD`. */
  day: string;
  /** How the caller originally entered the split — kept only so an edit can default back to the same input mode; the amounts owed are always `shares`, never recomputed from this. */
  splitMode: SplitMode;
  shares: SplitShare[];
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateSplitExpenseInput {
  /** Generated by the application (`crypto.randomUUID()`) before the write, so the shares' `expense_id` is known up front for a single batch (design.md). */
  id: string;
  groupId: string | null;
  payerUserId: string;
  createdByUserId: string;
  amount: number;
  currency: string;
  description: string;
  day: string;
  splitMode: SplitMode;
  shares: SplitShare[];
}

/** Every mutable field of an expense, replaced atomically. `group_id` and `created_by_user_id` are not here — they are immutable (design.md). */
export interface UpdateSplitExpenseFields {
  payerUserId: string;
  amount: number;
  currency: string;
  description: string;
  day: string;
  splitMode: SplitMode;
  shares: SplitShare[];
}
